import React from "react";
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { Search, MapPin, Calendar, Users, Filter, Heart, Share2, Star } from 'lucide-react';
const Accommodations = () => {
    const accommodations = [
        {
            id: 1,
            title: "Luxury Beachfront Villa",
            location: "Malibu, CA",
            price: 450,
            rating: 4.9,
            reviews: 127,
            image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
            features: ["Ocean View", "Private Pool", "5 Bedrooms", "WiFi"]
        },
        {
            id: 2,
            title: "Cozy Mountain Cabin",
            location: "Aspen, CO",
            price: 280,
            rating: 4.8,
            reviews: 89,
            image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=800&q=80",
            features: ["Mountain View", "Fireplace", "3 Bedrooms", "Hot Tub"]
        },
        {
            id: 3,
            title: "Modern City Loft",
            location: "New York, NY",
            price: 320,
            rating: 4.7,
            reviews: 156,
            image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
            features: ["City View", "Rooftop Access", "2 Bedrooms", "Gym"]
        },
        {
            id: 4,
            title: "Charming Country House",
            location: "Tuscany, Italy",
            price: 380,
            rating: 4.9,
            reviews: 203,
            image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&w=800&q=80",
            features: ["Vineyard View", "Garden", "4 Bedrooms", "Kitchen"]
        }
    ];
    return (React.createElement("div", { className: "min-h-screen bg-background" },
        React.createElement(Navigation, null),
        React.createElement("section", { className: "pt-24 pb-12 px-6 bg-gradient-to-br from-primary/20 to-secondary/20" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("h1", { className: "font-heading text-4xl md:text-6xl font-bold text-foreground mb-6 animate-fade-in" }, "Find Your Perfect Stay"),
                React.createElement("p", { className: "font-body text-xl text-muted-foreground max-w-2xl animate-fade-in" }, "Discover unique accommodations from cozy cabins to luxury villas"))),
        React.createElement("section", { className: "py-8 px-6 border-b border-border" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex flex-col lg:flex-row gap-4 items-center justify-between" },
                    React.createElement("div", { className: "flex-1 grid grid-cols-1 md:grid-cols-4 gap-2 bg-white rounded-2xl shadow-medium p-2 max-w-4xl" },
                        React.createElement("div", { className: "flex items-center gap-3 p-4 rounded-xl hover:bg-muted/50 transition-colors cursor-pointer" },
                            React.createElement(MapPin, { className: "w-5 h-5 text-muted-foreground" }),
                            React.createElement("div", null,
                                React.createElement("p", { className: "font-medium text-sm text-foreground" }, "Where"),
                                React.createElement("p", { className: "text-muted-foreground text-sm" }, "Search destinations"))),
                        React.createElement("div", { className: "flex items-center gap-3 p-4 rounded-xl hover:bg-muted/50 transition-colors cursor-pointer border-l border-border" },
                            React.createElement(Calendar, { className: "w-5 h-5 text-muted-foreground" }),
                            React.createElement("div", null,
                                React.createElement("p", { className: "font-medium text-sm text-foreground" }, "Check-in"),
                                React.createElement("p", { className: "text-muted-foreground text-sm" }, "Add dates"))),
                        React.createElement("div", { className: "flex items-center gap-3 p-4 rounded-xl hover:bg-muted/50 transition-colors cursor-pointer border-l border-border" },
                            React.createElement(Calendar, { className: "w-5 h-5 text-muted-foreground" }),
                            React.createElement("div", null,
                                React.createElement("p", { className: "font-medium text-sm text-foreground" }, "Check-out"),
                                React.createElement("p", { className: "text-muted-foreground text-sm" }, "Add dates"))),
                        React.createElement("div", { className: "flex items-center justify-between p-4" },
                            React.createElement("div", { className: "flex items-center gap-3" },
                                React.createElement(Users, { className: "w-5 h-5 text-muted-foreground" }),
                                React.createElement("div", null,
                                    React.createElement("p", { className: "font-medium text-sm text-foreground" }, "Guests"),
                                    React.createElement("p", { className: "text-muted-foreground text-sm" }, "Add guests"))),
                            React.createElement("button", { className: "btn-primary p-3 rounded-full" },
                                React.createElement(Search, { className: "w-5 h-5" })))),
                    React.createElement("button", { className: "btn-outline flex items-center gap-2" },
                        React.createElement(Filter, { className: "w-5 h-5" }),
                        "Filters")))),
        React.createElement("section", { className: "py-12 px-6" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center justify-between mb-8" },
                    React.createElement("p", { className: "font-body text-muted-foreground" },
                        accommodations.length,
                        " accommodations found"),
                    React.createElement("select", { className: "p-2 border border-border rounded-lg bg-background text-foreground" },
                        React.createElement("option", null, "Sort by: Recommended"),
                        React.createElement("option", null, "Price: Low to High"),
                        React.createElement("option", null, "Price: High to Low"),
                        React.createElement("option", null, "Rating: High to Low"))),
                React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8" }, accommodations.map((accommodation, index) => (React.createElement("div", { key: accommodation.id, className: "card-listing hover-lift cursor-pointer animate-slide-up", style: { animationDelay: `${index * 100}ms` } },
                    React.createElement("div", { className: "relative overflow-hidden rounded-t-2xl" },
                        React.createElement("img", { src: accommodation.image, alt: accommodation.title, className: "w-full h-64 object-cover hover:scale-105 transition-transform duration-300" }),
                        React.createElement("button", { className: "absolute top-4 right-4 p-2 bg-white/90 rounded-full hover:bg-white hover:scale-110 transition-all" },
                            React.createElement(Heart, { className: "w-5 h-5 text-muted-foreground hover:text-red-500" })),
                        React.createElement("button", { className: "absolute top-4 left-4 p-2 bg-white/90 rounded-full hover:bg-white hover:scale-110 transition-all" },
                            React.createElement(Share2, { className: "w-5 h-5 text-muted-foreground" }))),
                    React.createElement("div", { className: "p-6" },
                        React.createElement("div", { className: "flex items-start justify-between mb-3" },
                            React.createElement("div", null,
                                React.createElement("h3", { className: "font-heading text-xl font-semibold text-foreground mb-1" }, accommodation.title),
                                React.createElement("p", { className: "font-body text-muted-foreground flex items-center gap-1" },
                                    React.createElement(MapPin, { className: "w-4 h-4" }),
                                    accommodation.location)),
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(Star, { className: "w-4 h-4 fill-yellow-400 text-yellow-400" }),
                                React.createElement("span", { className: "font-medium text-sm" }, accommodation.rating),
                                React.createElement("span", { className: "text-muted-foreground text-sm" },
                                    "(",
                                    accommodation.reviews,
                                    ")"))),
                        React.createElement("div", { className: "flex flex-wrap gap-2 mb-4" }, accommodation.features.map((feature, idx) => (React.createElement("span", { key: idx, className: "px-3 py-1 bg-muted rounded-full text-sm text-muted-foreground" }, feature)))),
                        React.createElement("div", { className: "flex items-center justify-between" },
                            React.createElement("div", null,
                                React.createElement("span", { className: "font-heading text-2xl font-bold text-foreground" },
                                    "$",
                                    accommodation.price),
                                React.createElement("span", { className: "font-body text-muted-foreground" }, " / night")),
                            React.createElement("button", { className: "btn-primary" }, "Book Now"))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("button", { className: "btn-outline px-8 py-3" }, "Load More Accommodations")))),
        React.createElement(Footer, null)));
};
export default Accommodations;
