import React from "react";
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { Mountain, Clock, MapPin, Star, Heart, Share2, Users } from 'lucide-react';
const Experiences = () => {
    const experiences = [
        {
            id: 1,
            title: "Sunset Hot Air Balloon Ride",
            host: "Sky Adventures",
            location: "Napa Valley, CA",
            price: 280,
            duration: "3 hours",
            groupSize: "Up to 8 people",
            rating: 4.9,
            reviews: 234,
            image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
            category: "Adventure"
        },
        {
            id: 2,
            title: "Wine Tasting & Vineyard Tour",
            host: "Vine & Dine Tours",
            location: "Tuscany, Italy",
            price: 95,
            duration: "4 hours",
            groupSize: "Up to 12 people",
            rating: 4.8,
            reviews: 187,
            image: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80",
            category: "Food & Drink"
        },
        {
            id: 3,
            title: "Traditional Cooking Class",
            host: "Chef Maria's Kitchen",
            location: "Barcelona, Spain",
            price: 75,
            duration: "2.5 hours",
            groupSize: "Up to 6 people",
            rating: 4.9,
            reviews: 156,
            image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=80",
            category: "Cultural"
        },
        {
            id: 4,
            title: "Guided Mountain Hike",
            host: "Alpine Guides",
            location: "Swiss Alps, Switzerland",
            price: 120,
            duration: "6 hours",
            groupSize: "Up to 10 people",
            rating: 4.7,
            reviews: 289,
            image: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=800&q=80",
            category: "Adventure"
        }
    ];
    const categories = [
        "All Experiences",
        "Adventure",
        "Cultural",
        "Food & Drink",
        "Nature",
        "Art & History",
        "Sports",
        "Workshops"
    ];
    return (React.createElement("div", { className: "min-h-screen bg-background" },
        React.createElement(Navigation, null),
        React.createElement("section", { className: "pt-24 pb-12 px-6 bg-gradient-to-br from-muted/20 to-primary/10" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center gap-3 mb-4 animate-fade-in" },
                    React.createElement(Mountain, { className: "w-8 h-8 text-primary" }),
                    React.createElement("h1", { className: "font-heading text-4xl md:text-6xl font-bold text-foreground" }, "Unique Experiences")),
                React.createElement("p", { className: "font-body text-xl text-muted-foreground max-w-2xl animate-fade-in" }, "Discover unforgettable activities and local adventures crafted by passionate hosts"))),
        React.createElement("section", { className: "py-8 px-6 border-b border-border" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center gap-4 overflow-x-auto pb-2" }, categories.map((category, index) => (React.createElement("button", { key: category, className: `flex-shrink-0 px-6 py-3 rounded-full font-medium transition-all ${index === 0
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-muted hover:bg-muted/80 text-muted-foreground hover:text-foreground'}` }, category)))))),
        React.createElement("section", { className: "py-12 px-6" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center justify-between mb-8" },
                    React.createElement("p", { className: "font-body text-muted-foreground" },
                        experiences.length,
                        " experiences available"),
                    React.createElement("select", { className: "p-2 border border-border rounded-lg bg-background text-foreground" },
                        React.createElement("option", null, "Sort by: Recommended"),
                        React.createElement("option", null, "Price: Low to High"),
                        React.createElement("option", null, "Price: High to Low"),
                        React.createElement("option", null, "Rating: High to Low"))),
                React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8" }, experiences.map((experience, index) => (React.createElement("div", { key: experience.id, className: "card-listing hover-lift cursor-pointer animate-slide-up", style: { animationDelay: `${index * 100}ms` } },
                    React.createElement("div", { className: "relative overflow-hidden rounded-t-2xl" },
                        React.createElement("img", { src: experience.image, alt: experience.title, className: "w-full h-64 object-cover hover:scale-105 transition-transform duration-300" }),
                        React.createElement("button", { className: "absolute top-4 right-4 p-2 bg-white/90 rounded-full hover:bg-white hover:scale-110 transition-all" },
                            React.createElement(Heart, { className: "w-5 h-5 text-muted-foreground hover:text-red-500" })),
                        React.createElement("button", { className: "absolute top-4 left-4 p-2 bg-white/90 rounded-full hover:bg-white hover:scale-110 transition-all" },
                            React.createElement(Share2, { className: "w-5 h-5 text-muted-foreground" })),
                        React.createElement("div", { className: "absolute bottom-4 left-4 bg-white/90 rounded-full px-3 py-1" },
                            React.createElement("span", { className: "text-sm font-medium text-foreground" }, experience.category))),
                    React.createElement("div", { className: "p-6" },
                        React.createElement("div", { className: "flex items-start justify-between mb-3" },
                            React.createElement("div", null,
                                React.createElement("h3", { className: "font-heading text-xl font-semibold text-foreground mb-1" }, experience.title),
                                React.createElement("p", { className: "font-body text-primary font-medium mb-1" },
                                    "hosted by ",
                                    experience.host),
                                React.createElement("p", { className: "font-body text-muted-foreground flex items-center gap-1" },
                                    React.createElement(MapPin, { className: "w-4 h-4" }),
                                    experience.location)),
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(Star, { className: "w-4 h-4 fill-yellow-400 text-yellow-400" }),
                                React.createElement("span", { className: "font-medium text-sm" }, experience.rating),
                                React.createElement("span", { className: "text-muted-foreground text-sm" },
                                    "(",
                                    experience.reviews,
                                    ")"))),
                        React.createElement("div", { className: "flex items-center gap-4 mb-4 text-sm text-muted-foreground" },
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(Clock, { className: "w-4 h-4" }),
                                React.createElement("span", null, experience.duration)),
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(Users, { className: "w-4 h-4" }),
                                React.createElement("span", null, experience.groupSize))),
                        React.createElement("div", { className: "flex items-center justify-between" },
                            React.createElement("div", null,
                                React.createElement("span", { className: "font-heading text-2xl font-bold text-foreground" },
                                    "$",
                                    experience.price),
                                React.createElement("span", { className: "font-body text-muted-foreground" }, " / person")),
                            React.createElement("button", { className: "btn-primary" }, "Book Experience"))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("button", { className: "btn-outline px-8 py-3" }, "Load More Experiences")))),
        React.createElement(Footer, null)));
};
export default Experiences;
