import React from "react";
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { Sparkles, Clock, MapPin, Star, Heart, Share2 } from 'lucide-react';
const Services = () => {
    const services = [
        {
            id: 1,
            title: "Luxury Spa Treatment",
            provider: "Serenity Wellness",
            location: "Beverly Hills, CA",
            price: 180,
            duration: "90 min",
            rating: 4.9,
            reviews: 87,
            image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
            category: "Wellness & Spa"
        },
        {
            id: 2,
            title: "Private Chef Service",
            provider: "Gourmet At Home",
            location: "Manhattan, NY",
            price: 320,
            duration: "3 hours",
            rating: 4.8,
            reviews: 156,
            image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=80",
            category: "Dining & Culinary"
        },
        {
            id: 3,
            title: "Personal Training Session",
            provider: "FitLife Trainers",
            location: "Miami, FL",
            price: 95,
            duration: "60 min",
            rating: 4.7,
            reviews: 203,
            image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80",
            category: "Fitness & Health"
        },
        {
            id: 4,
            title: "Photography Session",
            provider: "Moment Capture Studio",
            location: "San Francisco, CA",
            price: 250,
            duration: "2 hours",
            rating: 4.9,
            reviews: 124,
            image: "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?auto=format&fit=crop&w=800&q=80",
            category: "Photography"
        }
    ];
    const categories = [
        "All Services",
        "Wellness & Spa",
        "Dining & Culinary",
        "Fitness & Health",
        "Photography",
        "Beauty & Grooming",
        "Transportation",
        "Concierge"
    ];
    return (React.createElement("div", { className: "min-h-screen bg-background" },
        React.createElement(Navigation, null),
        React.createElement("section", { className: "pt-24 pb-12 px-6 bg-gradient-to-br from-secondary/20 to-accent/20" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center gap-3 mb-4 animate-fade-in" },
                    React.createElement(Sparkles, { className: "w-8 h-8 text-accent" }),
                    React.createElement("h1", { className: "font-heading text-4xl md:text-6xl font-bold text-foreground" }, "Premium Services")),
                React.createElement("p", { className: "font-body text-xl text-muted-foreground max-w-2xl animate-fade-in" }, "Enhance your stay with personalized services from local professionals"))),
        React.createElement("section", { className: "py-8 px-6 border-b border-border" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center gap-4 overflow-x-auto pb-2" }, categories.map((category, index) => (React.createElement("button", { key: category, className: `flex-shrink-0 px-6 py-3 rounded-full font-medium transition-all ${index === 0
                        ? 'bg-accent text-accent-foreground'
                        : 'bg-muted hover:bg-muted/80 text-muted-foreground hover:text-foreground'}` }, category)))))),
        React.createElement("section", { className: "py-12 px-6" },
            React.createElement("div", { className: "max-w-7xl mx-auto" },
                React.createElement("div", { className: "flex items-center justify-between mb-8" },
                    React.createElement("p", { className: "font-body text-muted-foreground" },
                        services.length,
                        " services available"),
                    React.createElement("select", { className: "p-2 border border-border rounded-lg bg-background text-foreground" },
                        React.createElement("option", null, "Sort by: Recommended"),
                        React.createElement("option", null, "Price: Low to High"),
                        React.createElement("option", null, "Price: High to Low"),
                        React.createElement("option", null, "Rating: High to Low"))),
                React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8" }, services.map((service, index) => (React.createElement("div", { key: service.id, className: "card-listing hover-lift cursor-pointer animate-slide-up", style: { animationDelay: `${index * 100}ms` } },
                    React.createElement("div", { className: "relative overflow-hidden rounded-t-2xl" },
                        React.createElement("img", { src: service.image, alt: service.title, className: "w-full h-64 object-cover hover:scale-105 transition-transform duration-300" }),
                        React.createElement("button", { className: "absolute top-4 right-4 p-2 bg-white/90 rounded-full hover:bg-white hover:scale-110 transition-all" },
                            React.createElement(Heart, { className: "w-5 h-5 text-muted-foreground hover:text-red-500" })),
                        React.createElement("button", { className: "absolute top-4 left-4 p-2 bg-white/90 rounded-full hover:bg-white hover:scale-110 transition-all" },
                            React.createElement(Share2, { className: "w-5 h-5 text-muted-foreground" })),
                        React.createElement("div", { className: "absolute bottom-4 left-4 bg-white/90 rounded-full px-3 py-1" },
                            React.createElement("span", { className: "text-sm font-medium text-foreground" }, service.category))),
                    React.createElement("div", { className: "p-6" },
                        React.createElement("div", { className: "flex items-start justify-between mb-3" },
                            React.createElement("div", null,
                                React.createElement("h3", { className: "font-heading text-xl font-semibold text-foreground mb-1" }, service.title),
                                React.createElement("p", { className: "font-body text-accent font-medium mb-1" },
                                    "by ",
                                    service.provider),
                                React.createElement("p", { className: "font-body text-muted-foreground flex items-center gap-1" },
                                    React.createElement(MapPin, { className: "w-4 h-4" }),
                                    service.location)),
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(Star, { className: "w-4 h-4 fill-yellow-400 text-yellow-400" }),
                                React.createElement("span", { className: "font-medium text-sm" }, service.rating),
                                React.createElement("span", { className: "text-muted-foreground text-sm" },
                                    "(",
                                    service.reviews,
                                    ")"))),
                        React.createElement("div", { className: "flex items-center gap-2 mb-4" },
                            React.createElement(Clock, { className: "w-4 h-4 text-muted-foreground" }),
                            React.createElement("span", { className: "text-sm text-muted-foreground" }, service.duration)),
                        React.createElement("div", { className: "flex items-center justify-between" },
                            React.createElement("div", null,
                                React.createElement("span", { className: "font-heading text-2xl font-bold text-foreground" },
                                    "$",
                                    service.price),
                                React.createElement("span", { className: "font-body text-muted-foreground" }, " / session")),
                            React.createElement("button", { className: "btn-primary" }, "Book Service"))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("button", { className: "btn-outline px-8 py-3" }, "Load More Services")))),
        React.createElement(Footer, null)));
};
export default Services;
